# Setup
title:            shader.in
tagline:          "Writings on Computer Graphics by Mahesh Venkitachalam"
description:      shader.in
logo:             images/shader_logo_128.png

url:                 https://shader.in/
baseurl:             /
paginate:            5
permalink:           /:title/

highlighter:      rouge

# About/contact
author:
  name:              Mahesh Venkitachalam
  url:               https://twitter.com/mkvenkit
  email:             info@electronut.in

github:
  repo:           https://github.com/mkvenkit  

# Gems
plugins:
  - jekyll-paginate


